### ISSUE TITLE
Suggestion: SMD Model Exporter Support

### ISSUE THREAD

**Issue by Escope12** [Perfare/AssetStudio#162]
Is it possible to add an Exporter to export SMD Models with Normals in Unity Studio?

**Comment by mafaca** [comment]
What SMD Model is? I can't find such file format even with Google. Some custom model format? If so it would be much better if you find some kind of FBX to SMD converter.

**Comment by RamChupi** [comment]
SMD is a different type of model file,such as DAE.SMD models usually can export models with normals (used to make shapes smooth),while FBX export in US is rather broken,with some polygons ending up weird.I'd say it'd be a useful format to export to.

**Comment by akderebur** [comment]
I also think an exporter for a different model format would benefit the project. I was working on the animation branch and I have seen that it is using a library called SB3Utility for handling the fbx export. Not only does it limit the way you can customize your export, it also causes some problems. I have explained it in a comment how the keyframe interpolation isn't done right : https://github.com/Perfare/UnityStudio/issues/87#issuecomment-365003827

Fbx can still stay, but I think an export feature to a model format that supports skinning/animation and also simpler than fbx is a good idea. SMD would be a good choice. I would also recommend the IQE format. I may even write an exporter for it myself if I find the time to do it.

**Comment by Escope12** [comment]
Do you guys agree with this suggestion?

**Comment by RamChupi** [comment]
I sure do,more formats would expand the boundaries of model ripping.

**Comment by mafaca** [comment]
There is also this topic https://github.com/Perfare/UnityStudio/issues/139 about normals and it turns out from same author. I don't know why you think that there are problems with normals in FBX. Normals are exported as they are represented in native Unity's format so you can't export them in any other way (and it doesn't depend on final export format). Why you are so confident that the problem is with FBX and not with the source model? Can you give an example of such comparison?

**Comment by RamChupi** [comment]
Surely FBX,i know cuz i've compared normals from OBJ models to FBX.Most noticable with mirrored models,obj has smooth boundaries while the mirroring boundaries are clearly visible with FBX models.Some models even have polygons with no normals when i export to FBX,while in OBJ the normals are just fine.

**Comment by mafaca** [comment]
Can you provide a file with such model? Maybe I can figure this problem out.
Do you export FBX with skin? I think skin misleads you.

**Comment by mafaca** [comment]
@akderebur, if you are familiar with programing, why don't you fix already implemented FBX exporter then? If Perfare is right then there is TCB value in StreamedCurveKey class for every key value. FBX format supports TCB interpolation natively so you don't even have to convert them. All you need is to replace SB3Utility with other FBX lib that support slopes.

**Comment by RamChupi** [comment]
https://drive.google.com/file/d/1Psbq6_PQ-Yvp3Pl-6JKPBQw05PTOhWLf/view?usp=sharing
https://drive.google.com/file/d/1C90S4wUQy8K2rmr-fRqm4oURHh-DNQKy/view?usp=sharing
http://prntscr.com/iv34l5 Left is OBJ,right is FBX.

**Comment by mafaca** [comment]
I mean source Unity's asset file not exported one.

**Comment by RamChupi** [comment]
Oh,lemme get 'em

**Comment by RamChupi** [comment]
https://drive.google.com/file/d/1E5_lERZ7-nOWCX1GHAwuNOH-oZ6Z0uic/view?usp=sharing Might need some other files,unsure tho

**Comment by mafaca** [comment]
Well, I tested all possible options and here are results:
https://ibb.co/kvq1VH - looks OK
https://ibb.co/fzJYcx - this is FBX export with Normal disabled
https://ibb.co/nbvqPc - looks OK
https://ibb.co/kx9vqH - looks OK
https://ibb.co/kaYc4c - looks OK
https://ibb.co/cAdzHx - looks OK
As you can see FBX export works fine. The reason why FBX model looks angular on your pic  is because your 3D model program can't read Normals from fbx file or something like that.

**Comment by akderebur** [comment]
@mafaca Yes, StreamedCurveKey has the tcb value. There are also in/out slopes for legacy animations. The problem isn't the US, it is SB3Utility.

Any reason why ASCII fbx export was abandoned in the animation branch? I mean wasn't it working as expected? I think the easiest way would be to revert to ASCII (if it is fine) and provide the slope data.

**Comment by mafaca** [comment]
I think Perfare tried to abandon ASCII because currently it is giant mess of code. But SB3Utility wasn't good choice for replacement, though. ASCII still in use in the animation branch, it is used for Scene Hierarchy export. Definitly, ASCII would be much easier for something simple like legacy animations but I'm not sure about generic one.
A few month ago I tried to implement  export for legacy animations. I wrote this code https://gist.github.com/mafaca/ae05fb84ad851a61a6326aa7a46f5b24 and got some results. It is very primitive however it can help if someone decide to make something working and final.

**Comment by akderebur** [comment]
Thanks for that. I will take a look, and try to build on to it when I have the time.

**Comment by mafaca** [comment]
I decided to implement ascii FBX exporter for my project, but at first make it work in US. Unfortunately I fcking tired from all this, so I abandon this idea. [Here](
https://mega.nz/#!yew2DZDJ!G6WDeRVQFeS6GkqsN6rMLjC_nw45w_InraKW1rodHgY
) is my work. FBX exporter works but may contains some bugs though. I couldn't embed this exporter into the application. Maybe somebody want to finish so go ahead.
Currently it support legacy anim export from structure view if Animation component present and there is only one SkinnedMesh.

**Comment by Perfare** [comment]
Is there have any SMD Model document or sdk?
Ascii FBX is very difficult to research, I can't find a detailed document about it.
Using FBX SDK to export FBX is a better choice.

**Comment by Escope12** [comment]
https://developer.valvesoftware.com/wiki/Studiomdl_Data

**Comment by Escope12** [comment]
@Perfare Which FBX SDK does this program use? Does it export models with normals?

**Comment by kim-sama** [comment]
Milkshape 3d can open .ojb files, you can use that to open them and export as .smd, that's how I convert them to .smd

**Comment by Escope12** [comment]
@kim-sama What are ojb files?

**Comment by Perfare** [comment]
In the absence of various documentation and sdk, I don't think SMD is a good choice. As an alternative, I will implement exporting gltf. #195

**Comment by Escope12** [comment]
What is gltf?

**Comment by Perfare** [comment]
@Escope12 https://www.khronos.org/gltf/
