### ISSUE TITLE
[Suggestion] - Dump log

### ISSUE THREAD

**Issue by HeresHavi** [Perfare/AssetStudio#198]
Hey there Perfare,

Maybe it's an idea to create some sort of dump whenever the program crashes. This could help you investigate the problem. All we have to do is send you the dump or the log file.

What do you think?

**Comment by fireundubh** [comment]
Most exceptions aren't hard to debug. If you need a minidump, you can use [goldshtn/minidumper](https://github.com/goldshtn/minidumper). To actually implement an automatic minidump is a whole other project because you really don't want do it from the failing process. For example, when you run a Unity game and take a look at running processes, you'll see that Unity spawns a crash reporter process that captures relevant crash data, but Unity (the company) also has an army of developers and testers who can make sure that process is as reliable as possible.
