### ISSUE TITLE
How to use animation clip file exported?

### ISSUE THREAD

**Issue by Coresi7** [Perfare/AssetStudio#208]
All of the animation clip was exported as .dat file, which I have no idea how to import them into unity. Is there any document to explain how to use them?

**Comment by RamChupi** [comment]
First of all,might wanna get the new version.Only the older versions export AnimationClips as .dat files since there was no way to export those back then.Once you get the new version,go in Asset List,select the desired AnimationClip and export it with the correct Animator using "Export AnimationClip with selected Animator" under the export options.You can also only export the Animator,since then it automatically goes looking for it's Animation Clips.

**Comment by xDShot** [comment]
>You can also only export the Animator,since then it automatically goes looking for it's Animation Clips.

I select all Animators and press Export selected assets, but nothing exported, only creates empty folders in Animator. What wrong?
