### ISSUE TITLE
How Do I Run AssetStudio?

### ISSUE THREAD

**Issue by mariosonic500** [Perfare/AssetStudio#209]
I know this might be a stupid question but there's no EXE file it seems, so how do I use it?

**Comment by epikus29** [comment]
you need to download it from the "Download the latest build version from **here**" link in the newest release

**Comment by Stellarspace** [comment]
You would need Visual Studio to build it from the source you downloaded or you can download the latest build here: https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts

**Comment by Bob-Bo** [comment]
> 
> 
> I know this might be a stupid question but there's no EXE file it seems, so how do I use it?
AssetStudioGUI.exe  is the executable that is in the zip file.

**Comment by Draco18s** [comment]
> you need to download it from the "Download the latest build version from **here**" link in the newest release

Cough.

![image](https://user-images.githubusercontent.com/1750680/118733493-fc29ad80-b801-11eb-95a4-750e2b85fba1.png)

**Comment by Mactastic1-5** [comment]
> > you need to download it from the "Download the latest build version from **here**" link in the newest release
> 
> Cough.
> 
> ![image](https://user-images.githubusercontent.com/1750680/118733493-fc29ad80-b801-11eb-95a4-750e2b85fba1.png)

Yeah, that’s what happens when you open a link from 2018.

**Comment by Draco18s** [comment]
> Yeah, that’s what happens when you open a link from 2018.

So you're saying that [the releases page](https://github.com/Perfare/AssetStudio/releases) which invariably points to to [a build](https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts) based off [this commit](https://github.com/Perfare/AssetStudio/commit/251854cc41ff08c7fd14d25c43ae9fa2fad887a4) from a month ago is an outdated link.

Because it has no build.

![image](https://user-images.githubusercontent.com/1750680/118748828-08bdfe00-b822-11eb-880b-c9c468515aef.png)

**Comment by Mactastic1-5** [comment]
> > Yeah, that’s what happens when you open a link from 2018.
> 
> So you're saying that [the releases page](https://github.com/Perfare/AssetStudio/releases) which invariably points to to [a build](https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts) based off [this commit](https://github.com/Perfare/AssetStudio/commit/251854cc41ff08c7fd14d25c43ae9fa2fad887a4) from a month ago is an outdated link.
> 
> Because it has no build.
> 
> ![image](https://user-images.githubusercontent.com/1750680/118748828-08bdfe00-b822-11eb-880b-c9c468515aef.png)

No, I'm not saying anything, and I'm not here to argue with you. If there's no build available for whatever reason, then maybe you should download the most recent build available or build it yourself.

**Comment by Draco18s** [comment]
> No, I'm not saying anything, and I'm not here to argue with you. If there's no build available for whatever reason, **then maybe you should download the most recent build available** or build it yourself.

Cool, where? Because *every single* build entry on appveyor shows the "no artifacts" message. And this repo does not link to any other download location, nor does any other download location show up in google. Very helpful to tell me to do something I objectively cannot do per prior message.

As for building it myself, I have started attempting to do so, however I am still missing required components (btw, real handy for the instructions say "you need the FBX SDK" and not actually *link* to it or mention *what version*); low priority task.

**Comment by Mactastic1-5** [comment]
> > No, I'm not saying anything, and I'm not here to argue with you. If there's no build available for whatever reason, **then maybe you should download the most recent build available** or build it yourself.
> 
> Cool, where? Because _every single_ build entry on appveyor shows the "no artifacts" message. And this repo does not link to any other download location, nor does any other download location show up in google. Very helpful to tell me to do something I objectively cannot do per prior message.
> 
> As for building it myself, I have started attempting to do so, however I am still missing required components (btw, real handy for the instructions say "you need the FBX SDK" and not actually _link_ to it or mention _what version_); low priority task.

This software is free.

**Comment by Draco18s** [comment]
I'm trying to *inform the developer of a problem* so that it can be fixed. You're just being spiteful for no reason.

**Comment by Mactastic1-5** [comment]
> I'm trying to _inform the developer of a problem_ so that it can be fixed. You're just being spiteful for no reason.

You quoted me on a closed issue. If you're having a problem, create an issue.
