### ISSUE TITLE
Hi animation Dont work pls fix

### ISSUE THREAD

**Issue by godskin** [Perfare/AssetStudio#253]
here pls master https://drive.google.com/open?id=14HHe7Dm9DYsz5-dusBG9IrZODa5W3tJX

**Comment by godskin** [comment]
Here Extrac File 400 MB : https://drive.google.com/open?id=1SGY4_oEKxvnKXcD_7Zsq4mC1PusR1aGn

**Comment by cesm1980** [comment]
I tested the 400mb package and in a older version (0.10.0.69) for example the animator " npc_clgz_069" wasn't exporting correctly (bad skeleton).

Then i tried the current version (0.10.0.82) and apparently it's fixed (not sure if it was fixed now or in a previous version between 69 and 82) since that animator and the following ones all seem to export with bound animations without problems :

npc_cz_089_w
npc_cz_089
npc_cyj_020
npc_cls_160
npc_clgz_069
boss_bgj_025

Not sure if all of the others not mentioned are fixed too since i only tested the ones above at random.

Method used : selecting the animators and then EXPORT\SELECTED ASSETS, wasn't necessary to select any AnimationClips.
