### ISSUE TITLE
Export scenario

### ISSUE THREAD

**Issue by 1dadou1** [Perfare/AssetStudio#29]
I am in export " level "file UV disordered condition
Only in the unity5 The game will appear this kind of circumstance 
Unity4 games won't have this kind of situation
![qq 20170302120957](https://cloud.githubusercontent.com/assets/26129828/23502315/5bc557a0-ff72-11e6-83b5-632dffbfd5ab.png)
![qq 20170302180115](https://cloud.githubusercontent.com/assets/26129828/23502314/5bc1beba-ff72-11e6-86f6-a638adebf7b3.png)

**Comment by MichaelPriebe** [comment]
I believe I have the same problem.

So I export these selected 3d objects and it looks like it just exports everything multiple times.
![](http://i.imgur.com/TIbIpSu.png)
![](http://i.imgur.com/VYI0mBm.png)

**Comment by 1dadou1** [comment]
我来自中国   我看到您也是中国的 所以我就打汉字了。 我的问题是在unitystudio导出场景模型时 如果是unity5做的游戏   场景的UV会错乱  而且会导出多个场景文件   如果是unity4做的游戏  场景是正常的  没有问题 如截图那样。

**Comment by 1dadou1** [comment]
http://pan.baidu.com/s/1eSqWmye
我把文件上传在这里  在导出unity5和unty4的  level名的文件时  你可以看出差别

**Comment by 1dadou1** [comment]
https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor&p=198418&viewfull=1#post198418   
这个工具似乎可以得到动画数据

**Comment by Perfare** [comment]
抱歉，这问题我没法解决

**Comment by MichaelPriebe** [comment]
Please at least try, we figured out its when you export static meshes, dynamic meshes export flawlessly.

**Comment by 1dadou1** [comment]
感谢您的回答，目前v0.6.6 版本很好用。

**Comment by Perfare** [comment]
@MichaelPriebe About your screenshot above, I can't find any problem you describe. In your screenshot, Iciclex (x) all use the same mesh just different in position and direction, because you are all checked, therefore UnityStudio export look like 'exported multiple times' as your screenshot. I think you just have to choose one then export, it will correct

**Comment by Perfare** [comment]
@1dadou1 恩，我先收回我前面说的话，然后你上传的两个文件都是unity4.x的？我在你上传的unity5里没有找到相关问题，最好指定一下文件。至于"导出多个场景文件"你看下是不是选择了多个相同mesh的场景，比如2楼的图，这时候你只需要选择其中一个导出应该就是没有问题的

**Comment by MichaelPriebe** [comment]
If I choose one it still exports way more than the icicle. It doesn't even export the texture correctly. This is obviously wrong. The file has about 5 root meshes, which all come together to be the world, and it's exporting the entire root mesh that it's assigned to instead of just the object. This causes it to not export the texture to and be untextured.

**Comment by Perfare** [comment]
@MichaelPriebe Because the game settings, meshes is merge into one mesh, About Icicle, the mesh name is ‘Combined Mesh (root: scene) 3’, I check if choose one like IcicleD (3) it will export only one mesh, So I really can't solve the problem that you say.
About texture, if you read code you can know it no relationship with mesh, But I can't solve this 'problem' too.

**Comment by MichaelPriebe** [comment]
Can you at least show the root meshes so we can export them, like UABE does. 
![](http://i.imgur.com/DgUsFmr.png)

If you can get them to export with textures that will be amazing.

**Comment by Perfare** [comment]
@MichaelPriebe In Unity3D, mesh and texture through GameObject to establish contact, without any direct contact. I think it is very difficult to export mesh with texture.
By the way, what about the multiple problem?

**Comment by MichaelPriebe** [comment]
When I look in UABE the Icicles are GameObjects though..

The multiple exporting problem is still a problem because exporting just one of the objects doesn't guarantee that the root object is rotated and scaled correctly. And I'd have to export many objects until I find out one of each that are assigned to the 5 root objects. This does not guarantee they also line up. It be best to just be able to export the root objects themselves.

**Comment by 1dadou1** [comment]
@Perfare 我认为level  名字的文件 实际上是关卡   它是把各种单个的模型组合成一个大的场景。可能是unity5 对这部了更改 所以UnityStudio在导出场景模型的时候会出现错误。你可以尝试加载我上传的unity5当中的level 名字的文件，他会把相关联的文件一起读出来，当你导出整个level文件时 unity5的 就会出现UV错乱的情况，这在unity4的游戏里不会发生。      
![1](https://cloud.githubusercontent.com/assets/26129828/23734621/28f7286e-04bb-11e7-9811-070b6c96cde3.png)
![2](https://cloud.githubusercontent.com/assets/26129828/23734620/28f6c388-04bb-11e7-9fe0-9e10457a4ef2.png)
![3](https://cloud.githubusercontent.com/assets/26129828/23734622/28f75ee2-04bb-11e7-9677-b30979842096.png)
![4](https://cloud.githubusercontent.com/assets/26129828/23734619/28f695c0-04bb-11e7-897a-4349bbf50b75.png)

**Comment by 1dadou1** [comment]
@Perfare 不能说是UV错乱   在3D模型里应该是它没法识别多重子材质了，  这个场景模型  应该用到了很多张贴图 ，但是这里它只加载一张贴图在整个模型上。

**Comment by 1dadou1** [comment]
当我在3DSMAX里做完修改  上方的模型  雷达实际上用的是这张贴图   
![6](https://cloud.githubusercontent.com/assets/26129828/23735207/236ba33a-04bf-11e7-9dcc-a1a3d224ca77.png)

**Comment by GalatasarayForever** [comment]
Michael, I suggest you strongly to try unityex. Its also a very very useful exporter. You export meshes as obj. You can easyly add them to blender with right coordinates and rotation and texture them.

**Comment by MichaelPriebe** [comment]
I just tried, the model is just extremely exploded. So far Unity Studio works the best, and none of the files have names in UnityEx.

The only problem with Unity Studio now is that the textures have to manually be applied. And this will take ages for big models.
