### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by deadinsidex** [Perfare/AssetStudio#341]
I know this is not really an issue but I'm new and I do not understand how to run asset studio as it has no .exe I moved to asset studio as an alternative for unity studio as that is outdated. I searched most of youtube to find irrelevant or useless tutorials to use a source code

**Comment by BowDown097** [comment]
Go under the "Releases" section (in that little bar on top of the zip preview with commits, branch, and contributors) and you'll find exe's there. Otherwise, if you want to play around with updates as soon as a commit comes out, click on the "build passing" button underneath the zip preview in the readme.

**Comment by Perfare** [comment]
Go to the "Releases" section and you will see the download address.
