### ISSUE TITLE
Vertex colors of the mesh

### ISSUE THREAD

**Issue by HeresHavi** [Perfare/AssetStudio#355]
Hey Prefare,

This is more a question rather than an issue.

How can I link or find the Shades for a specific Mesh? As you can see, in the preview, when enabling Shades in the preview, it shows all it's colors, and that's what I want. But as soon as I export the Mesh and open it in 3ds max, Cinema 4D, it has nothing applied to it. Is there something I need to do?

I would appreciate it a lot if you could help me.

![image](https://user-images.githubusercontent.com/39027816/51789062-822f0f80-2185-11e9-9662-279d56b8b3ac.png)

**Comment by Perfare** [comment]
This is not a shader, it is a vertex color, and obj does not support vertex colors.

**Comment by HeresHavi** [comment]
What format does support vertex colors? And is it possible for you to extract these in a different format?

**Comment by HeresHavi** [comment]
> This is not a shader, it is a vertex color, and obj does not support vertex colors.

What format does support vertex colors? And is it possible for you to extract these in a different format?

**Comment by Perfare** [comment]
Will try to add new format support vertex color.

**Comment by HeresHavi** [comment]
> Will try to add new format support vertex color.

That's very much appreciated man! <3

**Comment by Brian151** [comment]
i don't get, why with as much as people choose obj as an export format, no one bothers making an extension for the format to support the multitude of things it doesn't, currently. Especially vertex colors, this is laughably easy, assuming you understand in the first place how the source format stores them. 

Especially since most people don't have the money for something like Maya, which conveniently supports everything but locks the end-user behind yet another proprietary black box...

nothing personal against you, this is a complaint against the whole collective of people who ever thought to make model converters for, typically game formats, and either gave-up on obj, or left it as an essentially useless option... using obj as-is has caused data loss during conversions. using autodesk formats just left people with a closed ecosystem being their only real option to edit/use anything they ever exported. it irritates me so much!

**Comment by RedSparr0w** [comment]
Sorry, just checking, was this issue closed because you found a solution, or it was implemented?

I can't seem to figure out how to keep the vertex color data.

**Comment by HeresHavi** [comment]
> Sorry, just checking, was this issue closed because you found a solution, or it was implemented?
> I can't seem to figure out how to keep the vertex color data.

I never cared to follow up again. He mentioned he would **try** to add the new format support that supports vertex colors but I am not sure if he did so. So if you can't, then it means that it's not added to AssetStudio
