### ISSUE TITLE
Bug: AssetStudio sees lights/fx in model but does not extract.

### ISSUE THREAD

**Issue by blazingforest** [Perfare/AssetStudio#360]
Hey!
I'm getting this bug where although AssetStudio can see that there are lights/particle systems in a model, it is not able to extract the effects with the model and they do not appear when the model is dragged into unity. Bellow is a small sample of some of my caches I'm using, and all effects will most likely be under "FX_". If you need more bundles to take a look at feel free to reply asking for more.
https://drive.google.com/open?id=1GA0iXKQng-32yde_apg4O2yd3UoqndJU
BlazingForest

**Comment by blazingforest** [comment]
These bundles came from an old game that shut down in 2014, and as such are relatively old ( guesses are either Unity 4 or 3 ) and will be used to assist with a remake me and a couple of other developers are working on.

**Comment by alphadrive** [comment]
AssetStudio is designed primarily to extract _from_ Unity asset/bundles into formats readable by other programs (e.g. Blender and 3DS Max), rather than decompiling the assets back into their Unity Project forms. The problem with Unity lights/particle systems is that they can't be stored in the .FBX file format that AssetStudio exports to -- they're kind of their own thing that can't be exported out of Unity.

If Perfare doesn't mind the mention of other github projects here, I'd suggest looking at mafaca's [UtinyRipper](https://github.com/mafaca/UtinyRipper) project -- that one actually tries to reconstruct the original project folder in Unity format (though it doesn't handle monoscript). AssetStudio's more designed for porting from Unity into other platforms.

**Comment by BlazingForrest** [comment]
Oh OK, never mind then. Thanks for the help.

**Comment by blazingforest** [comment]
Oh OK, never mind then. Thanks for the help!
