### ISSUE TITLE
Mesh and Skeleton not exported correctly + Other small QoL

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/AssetStudio#37]
https://mega.nz/#!h0BGAATT!8ZUBgUEGTmsEuPSx0JGe72122rvMpca_zEGZ-pVMbq4 Unity 5.5.2p1

I know you can't into 3D stuff well, but in case it's just something else that might be fixable.

Also would it be possible to detect unity cache bundle files __data without needing .assetbundle file extension(None of the cache files have file extensions, currently it doesn't detect bundles without the file extension.

**Comment by Stellarspace** [comment]
According to the README, Unity Studio only supports up to 5.5.1f1. I didn't download the files you uploaded to Mega. "I know you can't into 3D stuff well" You mean, Unity Studio can't export serialized objects to the FBX format very well? Yes, it can't. There is another issue on here that is similar to this one I think. It detects by file extension, for it to detect files that don't have a file extension, the program would need to read the header and/or footer in hex. That would be nice to add instead of file extensions. Export folder doesn't work from what I've testing. Honestly, there should just be an Open and Open folder... button and then you'd be able to select a file and multiple files or a folder and multiple folders. Hopefully it checks subfolders too.

**Comment by KekMcGee** [comment]
"Can't into 3D" is in reference to https://github.com/Perfare/UnityStudio/issues/16

I guess it's probably because 5.5.2 is unsupported currently, haven't read the read me in ages. but if it's still an issue after it's supported this should stay open.

The bundle extracting isn't a big issue but would make things a lot quicker.

**Comment by Perfare** [comment]
I didn't find any difference between 5.5.2 and 5.5.1 for the time being, I can't solve this problem if it is

**Comment by Perfare** [comment]
These files do not contain any skeleton information, export is actually normal.
