### ISSUE TITLE
No file was loaded when loading individual .dat files

### ISSUE THREAD

**Issue by beanbeanbug** [Perfare/AssetStudio#370]
Been trying to extract a couple .dat files that I'm pretty sure are for images or other supported items. I'm kinda new to this application (and windows in general), so sorry if this question's stupid. 

I have installed the base requirement files-Microsoft Visuals C++ 2013 and 2015, NET, and Visual Studio.  When I choose to extract an entire folder, the green bar with file names will appear as if it's being loaded (along with names of what it's loading), but once it finishes, nothing appears, and it says "no file was loaded." Other files, such as .asset and FILE, can be ripped and messed with just fine. I don't have FBX SDK installed because I didn't really understand the directions about the include and library directory, but I'm not sure that would give me that error. 

Attached is a .dat file that I'm trying to extract (I had to zip it to upload it, since github doesn't like .dat files). I'm positive that the file is a png file, but whenever I try and run it through, I keep getting 'no file was loaded.' Is there some trick I have to do for .dat files?
[magiccard_00001.dat.zip](https://github.com/Perfare/AssetStudio/files/2934218/magiccard_00001.dat.zip)

Thanks!

EDIT: running on win10 VirtualBox, if that's relevant.

**Comment by Perfare** [comment]
This is not a unity3d file or encrypted.

**Comment by beanbeanbug** [comment]
Ah, so does that mean AssetStudio can't open .dat files? In order to open it, do I need to manually change the filetype to unity3d, then? 

Thanks!

**Comment by alphadrive** [comment]
@beanbeanbug the .dat file you uploaded doesn't have a recognisable header when opened with a hex editor, so AssetStudio (and likely every other program) has no idea what to do with its contents. Your game's probably doing something very specific with the .dat file to read image data from it (from a hex editor, there's nothing human-readable about the contents at all to give us a hint of whether it's PNG binary data, some kind of compressed archive or something else entirely).

Just changing its file extension won't do anything in AS's case, since I'm fairly sure AS works by looking for recognisable headers to figure out exactly what kind of Unity file it is.
