### ISSUE TITLE
Opening asset bundle manifests?

### ISSUE THREAD

**Issue by zifix** [Perfare/AssetStudio#432]
Hi,
I saw the code already detects ABMs:
https://github.com/Perfare/AssetStudio/blob/master/AssetStudio/ClassIDType.cs#L210
but ReadAssets doesn't handle them:
https://github.com/Perfare/AssetStudio/blob/master/AssetStudio/AssetsManager.cs#L326
Do you have any plans to support them in the near future? If you have a specification, I could also help contribute that feature...
BR
Zifix

**Comment by Brian151** [comment]
i would like to see this feature, too
although, it would probably be possible for someone to write a tool to export them
i have considered this, but am hoping i don't have to...

it seems this tool focuses a little too much on raw asset data, though
may probably just be because unity's format is arguably a little INSANE

but there are tons of assets not really exportable through this tool [or really, any] because the programs are not fully handling the linking of various assets to eachother

additionally, this one is focused almost entirely on actual 'assets' , and not data/code stuff, which manifests are.

now, if you're interested in the manifests, i'm guessing you're also looking-into multi-file webGL games? [as i'd assume stand-alones permanently store their bundles or cache them long enough for interception] just curious...

i really hope some day this tool can be a reliable catch-all for all unity bundles and their assets...

fact is, the asset bundle extractor is painful to use, and generates LARGE extra files i'd rather not deal with... but there's so many sub-formats this just doesn't support even for raw export...

**Comment by zifix** [comment]
I've been digging into the source code and come up with a "ListAssetNames" funcction:
`var manifest = manager.assetsFileList[0].Objects.Values.First(x => x.type == ClassIDType.AssetBundleManifest);

var test = ((List<KeyValuePair<object,object>>) TypeTreeHelper.ReadUType(manifest.serializedType.m_Nodes, manifest.reader)["AssetBundleNames"]).Select(x => x.Value);`

**Comment by Perfare** [comment]
AssetStudio only focuses on extracting asset files that can be used for images, audio, models, and more. Asset files in other formats are not considered. You can try other tools like UABE.

**Comment by Brian151** [comment]
the problem is any large game uses a manifest to point to 90-99.99_ % of the content fitting said description. 

and UABE does not really display/export those in a way they're nice to work with... 

as for only working on images,models,audio... unity is unfortunately an engine that relies too much on tying them together with code, specifically game objects. i've got tons of unity bundles i basically can't extract from because there's a hierarchy of assets controlled/linked by game objects.

**Comment by Perfare** [comment]
@Brian151 Image and audio are relatively independent assets, and extracting them does not require care about the game's code or GameObject.

**Comment by Brian151** [comment]
@Perfare 
Of all the unity games i have played lately, a small fraction used static images
Most used animated sprites with static images serving as individual frames, or as texture atlases

A small handful did not use unity's default animation system, so I could theoretically rip from them

Guess I'm adding a project to my list...

@zifix 
no promises, no deadlines, but might look on my profile in the near future...
