### ISSUE TITLE
Export Mesh with Materials

### ISSUE THREAD

**Issue by ForsakenWorld** [Perfare/AssetStudio#434]
When I exporting "Mesh" objects, it exports without materials, even if asset contains "Material" objects. Materials exports only if I export models as "Animator" in FBX. But:
1) I can't use FBX because 3D tool which I use doesn't support this format
2) Not all parts inside asset can be extracted using "Animator".

I want to ask the program author: Can you add the ability to extracting "Mesh" objects with "Material" (read "Material" and generate MTL file for OBJ mesh, for example).

I strongly tired to create and assign the materials manually.

Please, bring my request the life.

**Comment by Brian151** [comment]
1. a lot of people cannot... i don't use any programs that support it, either
2. probably because this tool is focusing entirely on the actual media part of assets, but an overwhelming percent of the assets you encounter are heavily dependent on some permutation of a game object to link them to others, or control how they're displayed

and then obj exports lacking everything but mesh and textures...

but yes, it'd be nice to get fully textured models...

**Comment by Perfare** [comment]
1.Most tools in my knowledge support the fbx format, even if your tool does not support it, you can easily find the conversion tool by searching.
2.In Unity, Mesh and Material are not directly related. It uses MeshRenderer to control multiple Mesh and multiple Material. A Mesh can exist in multiple MeshRenderers. Logically it is very stupid to go through Mesh to find Material.

**Comment by Brian151** [comment]
1. true, but it still can be a pain. i've also encountered a handful of obscure formats that this just isn't viable for. fbx i don't think is on the list, though
2. this is one of the more "minor" reasons i won't use unity in my projects... LAYERS!
too many, IMO

and it also serves to make extraction/decompilation a real pain
makes an obfuscated/encrypted flash file look like a joke, that's the worse an SWF can be, and there's usually STILL a way to get what you need from it!

**Comment by ForsakenWorld** [comment]
@Brian151 I use ZModeler2 for working with mesh, it doesn't support fbx. 3ds Max will break the normals if mesh use "face weighted normals" smoothing. And I don't use Blender.
I can create materials by myself, but some meshes (csr2) uses 1 material per object, but another meshes (nfs heat studio) uses 3-4 materials per object. Reassigning = pain.
That's why I open this issue. But I understand Perfare's comment, and... If he says "No" - ok.

**Comment by Brian151** [comment]
@ForsakenWorld 

i'm not saying i agree, either...
just...yeah...respecting his decision

anyways, looks like i might be messing with the unity format
with all due respect, i'm a bit annoyed at the shortfalls of every hacking tool i've found...
at this rate, the commercial one i stumbled upon is going to overtake these freeware, open source ones. i'd rather not see that happen, and i want to process the asset bundles i'm sitting on, including the sequel/re-make of candy mountain... [which i've never played, and possibly never will because it's a webplayer game...]
