### ISSUE TITLE
Backgroundless sprites not appearing correctly

### ISSUE THREAD

**Issue by swampatha** [Perfare/AssetStudio#454]
I am trying to export the sprites from Mario Kart Tour. While other people seem to have no problems with this, every time I try to export or view a backgroundless sprite, it appears like this with broken alphas. Any idea how to fix?
![image](https://user-images.githubusercontent.com/53765280/68171168-b4557500-ff40-11e9-80c8-8a6f5fdad762.png)

**Comment by K0lb3** [comment]
The Spritehelper doesn't seem to use the alphatexture.

to be specific,

m_Sprite.m_RD.alphaTexture


This issue can be caused by some texture compressions,
which separate images into RGB and A textures.
What you can see in this image is the pure RGB part,
which is missing the alpha channel that can be found in said object.

The alpha textures are usually compressed too,
so the decompressed result is usually an RGB image.
So far I could simply use any of the channels of the alpha image as alpha channel for the RGB image created from the original texture.

```python
			original_image = get_image_from_texture2d(texture.read(), False)
			alpha_image = get_image_from_texture2d(alpha_texture.read(), False)
			original_image = PIL.Image.merge('RGBA', (*original_image.split()[:3], alpha_image.split()[0]))
```
[UnityPy/export/SpriteHelper.py](https://github.com/K0lb3/UnityPy/blob/master/UnityPy/export/SpriteHelper.py)
that's what I used in my python port of AssetStudio and so far it works 🤔

**Comment by Perfare** [comment]
@swampatha This image should contains a black and white alpha texture, you need to extract them and merge them.
@K0lb3 I don't use alphatexture because most games don't use this too. Game creators usually use SpriteRenderer and Material to control this behavior. So I decided to let the users merge them themselves.
