### ISSUE TITLE
add noise in some animations when exporting them in fbx

### ISSUE THREAD

**Issue by Sozuke** [Perfare/AssetStudio#588]
For example the animations of "idolmaster cinderella girls", try changing the fbx version, the encoding and the bone size (in 0 most of the problems are fixed but there is still noise)

by noise I mean alterations in some frames the model rotates completely even though the animation does not, I suppose that when they are saved in 60fps when exporting them in 30fps they break

**Comment by Perfare** [comment]
According to your description, it may be a problem during conversion. Rotation in Unity uses Quaternion storage, but in fbx, it uses Euler storage, so when outputting fbx, we need to convert Quaternion to Euler. This will cause problems if the rotation exceeds a certain degree, I added EulerFilter that comes with Fbx to solve this problem, but it may not be able to solve it normally.
I suggest you upload source files and screenshots to describe the problem in detail so that I can try to improve it better.

**Comment by Sozuke** [comment]
[EXAMPLE.zip](https://github.com/Perfare/AssetStudio/files/5098191/EXAMPLE.zip)
