### ISSUE TITLE
Serialized Shaders?

### ISSUE THREAD

**Issue by DaAwsumPiderman** [Perfare/AssetStudio#84]
I'm trying to extract a specific shader from a game that I need. There's some code inside of it that I need to read in order to understand how it connects to the in game meshes. However, when I select the shader I receive a "Serialized Shaders cannot be read." message... I truly hope there's some way around this since I desperately need that shader. It's literally the only thing keeping me from finishing my project.

Any ideas?

**Comment by OkazakiNaoki** [comment]
You are using Unity 2017 right? Version 5.6 is still working.
I guess Unity have changed once again.
I want to extract original shader codes so bad but they were all serialized since Unity 5.
May I ask about the serialized shader? Anyway to decompile it? 
Even I want to read the serialized shader code... I can only figure out what properties it has.
Also I can read the material value info(via UABE).
However, there's no CGPROGRAM part !
Hope this will be solved one day.

**Comment by Perfare** [comment]
I added some features in the 0.8 version, now UnityStudio can read compressed Shader after Unity 5.3, but it does not work well on all Shader

**Comment by OkazakiNaoki** [comment]
What kind of use case is allowed? Default standard shader?
Every shader I saw is like "\0\0\0...".

**Comment by JWNJWN** [comment]
Having this same issue on a game that's built using Unity 2017.3, any updates?

**Comment by Perfare** [comment]
The serialized Shader can already be exported, although there is still a need to improve.
