### ISSUE TITLE
May be export animations?

### ISSUE THREAD

**Issue by RobertTopala** [Perfare/AssetStudio#87]

**Comment by Stellarspace** [comment]
No, you can't export animations with any Unity decompilers that I've seen.

**Comment by Avatarchik** [comment]
Here is a decompiler it can retrieve any resources before the whole project project http://devxdevelopment.com/UnityUnpacker

**Comment by Stellarspace** [comment]
It isn’t free and they want a lot of money for the full version.

**Comment by Avatarchik** [comment]
Let me look for free alternatives, with a diet, you can finish this Unity Studio, since they can do it ... I do not think it's more complicated than the other types, Now I am looking for different information to share with all

**Comment by Stellarspace** [comment]
To my knowledge, every other decompiler is free. It would be nice if the developers of Unity Studio could add features from that paid program to Unity Studio. I might buy a copy to rebuild a project.

**Comment by Stellarspace** [comment]
If I wanted to rebuild a project, it would cost $200. Sounds like a scam.

**Comment by Perfare** [comment]
this program use crunch.dll copy from UnityStudio, I don't know why he doesn't make one by himself.
also, Il2cpp related code copy from my another project, because they have a same mistake.
but I don't see any license in this program, I don't know what to say.

**Comment by Avatarchik** [comment]
We will try to refine UnityStudio)

**Comment by Stellarspace** [comment]
You don’t see a license in the program?

**Comment by Stellarspace** [comment]
> Functionality:
> - Opening of distribution files (Unity standelone files (win, MAC, linux), apk, ios) 
> - View scene structures
> - View resources content (text, images, sounds, meshs, scripts, scene objects)
> - View scripts source code (decompile)
> - Export resources and scripts (convert image asset to PNG, DDS, sound to WAV, export Mesh to .obj format, decompile assemblys and etc.)
> - Generate Unity Project
> 
> 
> - Make Unity project (to Unity5.6 fromat)
> - scenes (.unity) 
> - scripts (c#) 
> - models (with animation)
> - assets (images, sounds, mesh, font, video and etc.)
> - resources
> - prefabs
> - plugins
>  
>  - Replace content in assets: (for standelone games)
>    - replace images
>    - replace text 
>    - replace binary content
>    - change asset header fields
>    - Replace and view all strings in assembly
>  
>  
> Support Unity3D Asset types:
> - Texture2D (support convert to PNG)
> - TextAsset
> - Mesh (support convert to Obj format)
> - AudioClip
> - Videop content (avi..)
> - Animations (animation, anitmator, animation clip, animation controller)
> - Materials
> - Sprite
> - Font
> - Shader sript (old unity)
>   and other.. 
> 
> Export model to .unitypackage container
> 
> Export model To FBX format (base implamentation)
> 
> Formats resource file names:
> - level *;
> - * mainData;
> - CustomAssetBundle- *;
> - CAB- *;
> - BuildPlayer- *;
> - * .assets;
> - * .sharedAssets
> and other..
> 
> Opening Standelone (win, mac, linux) game
> 
> Opening APK files with the ability to view and export the contents of the package.
> - * .apk
> - * .xapk
> - * .obb
> 
> Opening Unity bundle files with the ability to view and export the contents of the package:
> - * .unity3d; 
> - * .unity3d.lz4; 
> - * .assetbundle; 
> - * .bundle; 
> - * .bytes

If they can do it, we can do it too.

**Comment by Stellarspace** [comment]
@Perfare The demo version available for download is limited. You can't preview scenes and assets, generate a Unity Project, export resources to a directory, export all prefabs, and make an APK.

**Comment by Avatarchik** [comment]
Yes there is a cropped version there is no code, you need a version, since the pre-release version was hacked quickly the author decided to cut out the functional with a demo version

**Comment by Stellarspace** [comment]
@Avatarchik I was wondering why there was literally no code within the demo. The developer is advertising on Unity Community Answers. I see that the pirated version is all over the Internet. Maybe if he didn't want so much money for it when most of it is public domain, people wouldn't be pirating it.

**Comment by Avatarchik** [comment]
Yes the price is high, he generally plans to reschedule as an online service ...
Here the developer says that there is no point in breaking, there are people who broke the versions of the leading)
http://4pda.ru/forum/index.php?showtopic=844763&
There in Russian (my native) but you can use an interpreter

**Comment by Stellarspace** [comment]
@Avatarchik The online service will fail just the same if people have to pay a premium price. All of the download links are dead and I don't advise posting links to a forums where they frequently upload illegal content.

**Comment by Stellarspace** [comment]
I would just like to point out that it isn't impossible to bypass the security he added to the program. He just made it more difficult.

**Comment by Stellarspace** [comment]
@Avatarchik Are you even allowed to sell software that includes DLLs that aren't yours?

**Comment by mafaca** [comment]
I research his project. Sad, but he exports models and animation to Unity's internal format, so u can't open it with Blender and change it if u want.
Btw, this internal Unity's format fairly easy to implement, so maybe UnityStudio should support it too?

**Comment by Avatarchik** [comment]
Btw, this internal Unity's format fairly easy to implement, so maybe UnityStudio should support it too? 
Yes!!!
Stellarspace (I'm not a developer DevXUnity-Unpacker Magic Tools)
 I want to make a free alternative!

**Comment by Avatarchik** [comment]
As it is still interesting to export the whole project, more precisely how it exports scenes and prefabs in general ...

**Comment by Stellarspace** [comment]
@mafaca With his program, you can only export to a Unity Package? Doesn't it say you can export to FBX? It's possible.

**Comment by Stellarspace** [comment]
@Avatarchik Building on Unity Studio is a good start to making a free alternative.

**Comment by Stellarspace** [comment]
@Avatarchik It is interesting how the program can create a Unity project from a .unity3d file. You can also view the 3D models and scenes within the program as well. You can see the DLLs the developer is using to do these things. I don't see why we wouldn't be able to decompile the program and add features to Unity Studio.

**Comment by Avatarchik** [comment]
In the demo version there is no functional, you need the full version to figure out what's what ...

**Comment by Perfare** [comment]
@mafaca It's a good idea, and I'll try to do it.

**Comment by Stellarspace** [comment]
@Avatarchik Correct, so if I were to pay for the $38 one, I should be able to do unlock the $258 one.

**Comment by Daniil1288** [comment]
@Stellarspace, just in case you didn't figure this out already: the download links on that Russian forum aren't dead, they appear in such a way (for no apparent reason) until you register. Had to find that out the hard way...

**Comment by Stellarspace** [comment]
@Daniil1288 I didn't figure it out, I thought the links were actually dead. Thank you. Are any of them the activate version?

**Comment by Stellarspace** [comment]
Rebuilding the project doesn't work properly. When I open it in Unity, it crashes. I wonder if it works on the newer version.

**Comment by Stellarspace** [comment]
@Daniil1288 The developer doesn't even respond to emails. Why should I buy a product that doesn't work for what I need it for?

**Comment by JuGGerNaunT** [comment]
Unity's plugin https://assetstore.unity.com/packages/essentials/fbx-exporter-beta-101408 allows u to export Unity's internal format to FBX, so US definitely should support this internal format.

**Comment by Perfare** [comment]
Even if I lack of 3d model knowledge. I still finished this feature.
check [here](https://github.com/Perfare/UnityStudio/tree/animation)
I only tested Honkai Impact 3, I think it working fine.
But there are still many things that need improvement.

**Comment by mafaca** [comment]
Wow. It is good news to hear that. Definitely, huge step forward to significant improving US.
But it is sad to see that only new Animator component is supported. I hope u r planning to implement separation AnimationClip export, because old Animation component isn't work now. Besides, Animation Clip can be ship in separate asset bundles, so there is neither Animator or Animator component at all. As I remember it would be problems with AnimClip heirarchy if no mesh present in asset bundle, but I hope u could handle this case ) 
Anyway, even Animator dont work perfect yet. I tested it with animations from my work project and got nothing. FBX exported as binary type so i cant even tell on which state issue occures - on export or on Unity import.
By the way, when i tryed to implement animation export,i faces the problem with high angle rotations. I cant test it, but i hoped ur work dont have such issue.

**Comment by Perfare** [comment]
@mafaca I will continue to support Animation and separate AnimationClip
I also tested some files like this #116 , looks like it work fine.
In addition, in order to be able to export successfully, load assets and their all shared files to creating a complete Transform path is required

**Comment by mhoangvslev** [comment]
I really think the mesh export with skeleton has to be completed first. In games like Verdun, meshes are not in good order.

**Comment by JuGGerNaunT** [comment]
US requires more contributors in order to implement all desirable features. As i know, issue from this topic https://github.com/Perfare/UnityStudio/issues/104 still actual for FXB export. We need someone either who can fix it or write same unpacker as in project above.

**Comment by Perfare** [comment]
@mafaca Because export AnimationClip need Animator(Avatar) to get bone name info, So I finally added a new export method.
You need to import the model and the animation assets together, use ctrl to select Animator and AnimationClip, Export - Animator with AnimationClip will work

**Comment by Aircoookie** [comment]
Hi Perfare,
first off all, thank you for your awesome work! I successfully managed to export a FBX model with bones and textures (T-Pose)! Now I'd also like the animations for that character. So I tried your latest animation branch. Indeed I was able to find and export the AnimationClip file I wanted. However, I only get a file without a file extension which I can't import into Unity or any other application. You've mentioned I'd also need an Animator(Avatar) file, however I was unable to find that type of file in the Asset list. Do you have any idea where I could find this Animator Controller file?
This may sound like a stupid question since I have no experience with Unity whatsoever, I'd just like to retrieve the model in the pose from the game for 3D printing.
If it matters, I'm trying to get the "E3_S01B_Rachel_I_CurledUp" pose from the third episode of Life Is Strange before the storm (Rachels Room).
Thank you so much for this!

**Comment by Perfare** [comment]
@Aircoookie I can't know where Animator is, you can try to load all the asset files

**Comment by Nifty255** [comment]
@Perfare I've noticed 2 things in your animation branch that might be of importance.

Firstly, the Animation class isn't properly loading and therefore crashes any attempted export which involves them. It appears the class is misreading the number of AnimationClip pointers in the array. If this could be fixed, you're well on the way to a really easy solution for exporting animations, which brings me to my next point.

Instead of worrying about manual exporting of Animators and their clips, why not directly tie that into exporting 3D objects? During the FBX export process, you can search each GameObject for an Animation OR Animator component and then use the same functions you're using already to hit 2 birds with one stone and just write all of the associated clips directly into the 3D object FBX you're exporting.

**Comment by Perfare** [comment]
@Nifty255 This is my mistake. I've fixed it.
"exporting 3D objects" is export ascii FBX file, if I want to add functionality to the old code, I need time to research the ascii FBX format.

**Comment by Perfare** [comment]
@mafaca I wish you success

**Comment by Perfare** [comment]
@Nifty255 In my plan, I will keep "export 3D object" and add a new option like "export 3D object (binary)"

**Comment by Nifty255** [comment]
Awsm.

**Comment by Nifty255** [comment]
Honestly, I wish you could just directly export AnimationClips to the Unity.anim format, but there's something in Unity preventing them from being properly recognized so you can't use them.

**Comment by mafaca** [comment]
As I see, currently animation export don's properly handle such situation as when Quaternion rotation shift from -170 to 170 degrees (which mean -190 euler). At least it look like so, because I also faced this issue when i tried to implement FBX animation export myself.

**Comment by mafaca** [comment]
Finally I released yaml exporter in my repository. It's a separate module which can be easily included in other project. I added console application with command line for test and as an example.
Currently it supports prefabs, meshes, meshrenderers, skinnedmeshrenderers, animator, animation, avatars, legacy and generic animationclips, textassets and old shaders. In the near future I'm going to add support for 5.3-5.4 and serialized shaders.

**Comment by atomixnmc** [comment]
Hi, just pass by and want to say i really appreciate all your effort in developing the tools and this feature. I'm diving into the code right now and really feel the urgent of cracking this last bit! 

I have a vision of exporting the whole asset bundle into an opinioned well-form unity project structure including source code. Animation is an important part of the process so i will stay tune with this thread's notification.

**Comment by akderebur** [comment]
I was looking at getting the legacy animations to export, using the clips from the Idolmaster game. So I was able to populate the track using the keyframe values in translation/rotation curves. There seems to be no problem with those values, but it looks like the keyframe interpolation isn't right.

It is probably because the in/out slope of the keyframes isn't taken into consideration during the interpolation. I couldn't find a way to provide that information to SB3Utility.

First I exported the animation just using the keyframes, and it looked like this :
![NoInt](https://i.imgur.com/eD2bfBH.gif)

You can see that there are some weird hand movements. I think the reason is the wrong interpolation, since it happens between keyframes.

After that I tried interpolating via code, before passing the frames to SB3Utility. So the value of the curve would be evaluated at each frame, and added to track, as if it is a keyframe. That fixed the hand movements but made the animation a bit jittery overall (this isn't the best way to do it anyway) : 
![Int](https://i.imgur.com/n2yG4tT.gif)

I don't know if there is a way to fix this. Maybe it is possible to pass slope data to SB3Utility, but I didn't notice? If not, it might be easier to achieve that using ASCII FBX.

This stuff is mostly related to the exporter library, but I still wanted to let you know. Keep up the great work.

**Comment by Perfare** [comment]
@akderebur Can you upload a file?

**Comment by akderebur** [comment]
Here you go : [Sample Files](http://www.mediafire.com/file/61znduk59xcxaz4/IMSample.rar)

One of the files has mesh and animator, other one has the clip. Both are bundle files.

**Comment by Perfare** [comment]
@akderebur I think the big probability is Quaternion To Euler problem
I use @mafaca code to improve QuaternionToEuler and tested these files, now it looks like the export is more perfect.

**Comment by Perfare** [comment]
AssetStudio can now export animations. Although there are still many things that need improvement, I think this issue can be closed first.

**Comment by xGitHubUser999x** [comment]
Hey Perfare.

Please tell me step by step how to export animations to FBX format? 

Thanks.)

**Comment by mhoangvslev** [comment]
@xGitHubUser999x 
Hello, it's easy:
- Filter loaded assets by name from the Asset List
- Using Ctrl + LMB, select the Animator first, then the desired animations.
- Export Selected (you will have an fbx with multiple animation slots)

**Comment by xGitHubUser999x** [comment]
For some reason it does not work for me.
I get 2 folders ('Animator' with 'Animator #00253.dat' file inside and 'AnimationClip' with 'idleshow.dat' file inside) when I use Export-->Selected assets and not a single FBX file.

**Comment by mhoangvslev** [comment]
@xGitHubUser999x 
My mistake, Export -> Export Animator with AnimationClip

**Comment by mhoangvslev** [comment]
@xGitHubUser999x You must to have the latest version of the repository. After that, there are few additional steps to take, as referered in #175

**Comment by xGitHubUser999x** [comment]
Thank you for you reply.

I'm using the latest version of program (UnityStudio.x64.v0.9.0.zip). 
I exported all the necessary meshes to FBX format and textures to PNG format without problems.
However, I can't export animations to FBX format, because there is no "Export Animator with AnimationClip" option.
I tried another version of the program (UnityStudio.v0.9.0.zip), but neither Animator nor AnimationClip files don't appear in Asset List.(

I have the following applications installed:
Autodesk FBX SDK 2018.11
Microsoft Visual C++ 2015 RC Redistributable (x64) - 14.0.22816
Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24215
Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24215

If I understood you well, I need to uninstall FBX SDK 2018.11 and install FBX SDK 2015, but where I can download it?

Also Perfare said that AssetStudioFBX.dll uses FBX SDK 2015, but inside UnityStudio.x64.v0.9.0.zip there is no AssetStudioFBX.dll.  

I'm now even more confused.
